[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root"]

[start]
cmd = "mkdir -p /data/storage && python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8080"
